### PR TITLE
Tweaks to template deployability

### PR DESCRIPTION
**Pull request by ctseto**
Reactions file parsed for organelle/compartment names: chloroplast,
plastid, etc, and used to augment exclusion.

Human Reactions.tsv adjusted to include additional compartments, including
carboxysome, golgi, lysosome, mitochondria, nucleus, endoplasmic
reticulum, peroxisome.

Mycobacteria compartments now cytosol, extracellular and periplasm.

Microbial templates also cytosol, extracellular, periplasm.

Microbial, Human, Mycobacterial templates have rxn07191. However
cpx31109 appears to no longer exist. To get these templates to work,
cpx31109 is excised.

Microbial, Human, Mycobacterial templates were test-built on local
environment, and appear to build successfully without problems.

Issue: Reactions.tsv was built using GramNegative template as a starting point. However, in those templates only reactions 1->14399 have associated complexes. Reactions beyond 14399 do not presently have associated complexes, thus type is gapfilling instead of conditional.

### CODE REVIEW

**Comment by chian** [comment]
@cseto Is there a plan to approach the complexes issue? 

@mmundy Does this get resolved by latest ProbModelsEED integration?

**Comment by cseto** [comment]
Looks like there was a typo: @ctseto is your intended recipient. I'm @cseto.

**Comment by chian** [comment]
@ctseto

**Comment by mmundy42** [comment]
Yes, and with the curation that is being done to the model templates.

**Comment by ctseto** [comment]
@chian Haven't had much luck finding a reference that links all reactions with all complexes. Complexes and roles are better related. 

./Mappings/ComplexRoles.kegg.tsv describes the relationship between complexes (older cpx) and roles (fr), for those in the KEGG database. This file is akin to the Roles.tsv in ./Templates.

./SOLRDump/ComplexRoles.tsv also has a file describing the older complexes (cpx) and roles (psfr).

./Templates/Complexes.tsv lists complexes (cpx...), names (mscpx., cpx., pscpx.,)  and associated roles(ftr); and ./Templates/Roles.tsv has roles (ftr), a reaction name string and additional aliases (msfr, psfr). Cross-referencing reaction name strings from Roles.tsv with the associated reaction names in reaction.master.tsv did not generate a large number of matches. It turns out that the reaction names in Roles are less processed than those in those in reactions.master.tsv; thus applying some processing (changes in letter case, elimination of special characters and EC number) may increase the match count.

**Comment by cseto** [comment]
Please remove @cseto from this discussion, thanks.

**Pull request merged**
