### PR TITLE
Update of InChIKey and SMILE in compounds

### PR DESCRIPTION
**Pull request by samseaver**
An important note is that if there was any apparent conflict between InChIKey or SMILE strings for the same listed compound, currently nothing is listed in the compounds file. The same conflicts will be reported independently, and used to curate the biochemistry moving forward.

Users can still find the conflicting structures in the Biochemistry/Structures folder.

### CODE REVIEW

**Comment by samseaver** [comment]
I'm closing this, I just realized that I may not be including the proton count for compounds which have been correctly charged.

**Comment by samseaver** [comment]
Addressed my concern, I'd done it right, but I also added back in the original InChI so that it's easier to parse.

@cshenry @JamesJeffryes I'd like to merge this PR shortly, but we will discuss this at the next Jam.

**Comment by JamesJeffryes** [comment]
@samseaver Do you want me to review this PR?

**Comment by samseaver** [comment]
Yes, in that the inchikey and smiles field in the compounds is filled appropriately

**Pull request closed without merging**
