### PR TITLE
Templates

### LINKED ISSUE #48: Imbalanced reaction in templates
rxn04656 is one such example. Validation tests should verify an "OK" status for any reaction that appears in a template

### PR DESCRIPTION
**Pull request by JamesJeffryes**
This PR updates the templates by replacing reactions marked as obsolete in the template with a valid linked reaction. Also, reactions that were not atom balanced were removed from the template. (only 9 from core & gram +&- but many more from human & mycobacterial templates) The Validate Template file has been updated to check for obsolete and imbalanced reactions on travis. 

I've requested review from those that might have an opinion on changes to the templates.

Fixes #48

### CODE REVIEW

**Comment by JamesJeffryes** [comment]
From @mmundy42:

>  I spot checked a few reactions and it looks like that in the biochemistry
> the reactions have a status that does not include “OK”. For reactions that
> have a type of “gapfilling” it should be fine to remove them from the
> template. But I did notice that some of the reactions have a type of
> “conditional” which means they are linked to a complex and a role. I would
> prefer to keep conditional reactions since they improve the reconstruction
> of draft models.

Does this sound like a good compromise? I would change the validation to allow imbalanced reactions if they are conditional.

**Comment by mmundy42** [comment]
Yes, that is a good compromise. We can review later and figure out if the troublesome reactions can be replaced by reactions that have OK status.

> Does this sound like a good compromise? I would change the validation to allow imbalanced reactions if they are conditional.

**Comment by samseaver** [comment]
Unbalanced reactions should never be allowed in the template, but if there are conditional reactions that are unbalanced, they should either be fixed directly, or replaced with the appropriate balanced reaction.

Since these files have not yet been updated from the current objects being used in production, I have no problem removing them for the time being so that the checks pass, but we should maintain a separate file (added to this PR if possible) that lists: The reaction being removed and the template it was found in.

When time comes to actually maintain the templates through this repository, we'll have to curate these.

**Comment by janakagithub** [comment]
James, do you save those unbalanced reactions from core/gram-/+ templates? I think some of those are key reactions (may be all the reactions), those need to be atom balanced and added back to the template.

**Comment by JamesJeffryes** [comment]
Here are the reactions that are imbalanced. Some reactions like DNA synthesis cannot be balanced but we can change the status to OK if we want to keep them.
[imbalanced rxns.txt](https://github.com/ModelSEED/ModelSEEDDatabase/files/1166603/imbalanced.rxns.txt)

**Comment by JamesJeffryes** [comment]
@janakagithub @jplfaria Do you want to attempt to balance these reactions?

**Comment by chian** [comment]
Just as a note, I don't think many of these reactions are not going to be balanced because they are sinks into concepts like "protein synthesis ". And they involve fractions of things. Also, even if you do give a concept a molecular formula, it would eventually ruin the point as something like protein synthesis is probably meant to change amino acid ratios.

**Comment by JamesJeffryes** [comment]
So I changed approach on this. The Mayo Clinic templates are exempt from validation while I was able to update or balance reactions for all but rxn01659. This reaction produces a plant hormone and is only used for gapfilling so I think it's reasonable to drop.

**Comment by JamesJeffryes** [comment]
So I'm going to close this PR and make the changes in the JSON files

**Pull request closed without merging**
