### PR TITLE
Updating a notes column to store code from different processes

### PR DESCRIPTION
**Pull request by samseaver**

### CODE REVIEW

**Comment by JamesJeffryes** [comment]
@samseaver Does this incorporate any of the changes I made in my PR? If you could merge in my changes to reactions before updating the schema it should resolve the conflict.

**Comment by samseaver** [comment]
I hadn't incorporated those changes, but, though I can merge from there, you had an problem in how you changed the formula of the fatty-acyl ACPs, it shouldn't be hard to fix, but once you've done so, I can merge your changes.

**Comment by samseaver** [comment]
Oh, I just realized you were talking about the current state of master. I'll merge that.

**Comment by samseaver** [comment]
So, I think I figured it out, can you double-check that this has your recent commits?

**Comment by JamesJeffryes** [comment]
I'm going to merge this and update my own PR to match this new schema

**Pull request merged**
