### PR TITLE
Update ontology objects and ontology object generation/loading scripts

### PR DESCRIPTION
**Pull request by janakagithub**
Ontology objects added and updated:
KBaseOntology.OntologyDictionary.EBI_EC_ontologyDictionary.json
KBaseOntology.OntologyDictionary.KEGG_KO_ontologyDictionary.json
KBaseOntology.OntologyDictionary.KEGG_RXN_ontologyDictionary.json
KBaseOntology.OntologyDictionary.MetaCyc_RXN_ontologyDictionary.json
KBaseOntology.OntologyDictionary.ModelSEED_RXN_ontologyDictionary.json
Ontology Translational objects
KEGG Rxn -> ModelSEED
EC -> ModelSEED
MetaCyc ->ModelSEED

### CODE REVIEW

**Comment by samseaver** [comment]
I don't have a problem with this merger, but I'm concerned about where the MetaCyc ontology came from, did you download a recent release of the database? I've got version 22.5 in my MetaCyc mirror. What is the MetaCyc XML file?

**Comment by janakagithub** [comment]
Scripts that I have setup parse MetaCyc ->ModelSEED ontology translations from  ModelSEEDDatabase/Biochemistry/Aliases/Provenance/Reactions_Aliases.tsv
Upon updating Reactions_Aliases.tsv ontology translations would update as well. As for the MetaCyc dictionary, it was generated using the MetaCycReactionsFull.xml produced from Jeff at LLNL, which I believe is upto date.

**Comment by samseaver** [comment]
@janakagithub OK if the xml file was generated directly from MetaCyc, I'd rather not keep it in the repository to avoid any potential licensing issues, can you remove only the xml file? We can keep any derived and re-organized data.

**Comment by janakagithub** [comment]
Metacyc Reaction file removed from the PR.

**Comment by samseaver** [comment]
OK, thanks, looks good.

**Pull request merged**
