### PR TITLE
Adding structures

### PR DESCRIPTION
**Pull request by samseaver**

### CODE REVIEW

**Comment by JamesJeffryes** [comment]
@samseaver This broke the tests b/c the JSON schema for compounds must be updated to match the new format. I'll push an update to the branch

**Comment by samseaver** [comment]
Can you point me to an example code stub that validates a JSON using a schema?

**Comment by JamesJeffryes** [comment]
@samseaver Here's an example https://github.com/ModelSEED/ModelSEEDDatabase/blob/master/Scripts/Validation/Validate_Compounds_JSON.py#L10

**Comment by JamesJeffryes** [comment]
Note the switch to using the inchikey instead of structure field to find duplicates will result in new errors and a failing build

**Pull request merged**
